name: BTC Scanner Automation

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-btc-scan:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      ALLOWED_CHAT_IDS: ${{ secrets.ALLOWED_CHAT_IDS }}
      OWNER_ID: ${{ secrets.OWNER_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install requests; fi

      - name: Run BTC Scan once
        run: |
          python run_once.py
